// Generated by OrchestKit Claude Plugin
// Created: 2026-08-04

import { AUTH_EVENT_FAMILY, truncateForAnalytics, generateUUID } from '../authEventFamilies';

describe('AUTH_EVENT_FAMILY', () => {
  test('maps register to sign_up', () => {
    expect(AUTH_EVENT_FAMILY.register).toBe('sign_up');
  });
  test('maps login to login', () => {
    expect(AUTH_EVENT_FAMILY.login).toBe('login');
  });
});

describe('truncateForAnalytics', () => {
  test('returns undefined for null/undefined', () => {
    expect(truncateForAnalytics(null)).toBeUndefined();
    expect(truncateForAnalytics(undefined)).toBeUndefined();
  });
  test('leaves short strings unchanged', () => {
    expect(truncateForAnalytics('short message')).toBe('short message');
  });
  test('truncates to exactly 100 chars', () => {
    const longString = 'x'.repeat(150);
    const result = truncateForAnalytics(longString);
    expect(result.length).toBe(100);
    expect(result).toBe('x'.repeat(100));
  });
  test('leaves a value exactly 100 chars unchanged', () => {
    const exact = 'y'.repeat(100);
    expect(truncateForAnalytics(exact)).toBe(exact);
  });
  test('stringifies non-string input before truncating', () => {
    expect(truncateForAnalytics(404)).toBe('404');
  });
});

describe('generateUUID', () => {
  test('matches RFC 4122 v4 UUID shape', () => {
    const uuid = generateUUID();
    expect(uuid).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
  });
  test('generates unique values across calls', () => {
    const ids = new Set(Array.from({ length: 50 }, () => generateUUID()));
    expect(ids.size).toBe(50);
  });
});
