// Generated by OrchestKit Claude Plugin
// Created: 2026-08-10

'use strict';

/**
 * Auth surface for the app: SSO/social sign-in, email login/register, JWT
 * storage in the OS keychain, token refresh, and the one-time migration off
 * the legacy AsyncStorage token.
 *
 * This module is a plain object of methods that api.js spreads into
 * `Sefaria.api`, so every existing `Sefaria.api.<authMethod>` call site keeps
 * working unchanged. Methods therefore still call each other through
 * `Sefaria.api.*` rather than through a local reference -- that indirection is
 * what lets tests stub individual methods, so don't "clean it up".
 *
 * Nothing here imports api.js: the only thing it needs from the api object
 * (`_baseHost`) is read off the global `Sefaria` at call time, which keeps the
 * two modules acyclic.
 *
 * NOTE: `Sefaria.api._baseHost` ends with a trailing slash and every endpoint
 * below is concatenated with NO leading slash. Keep that convention.
 */

import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Keychain from 'react-native-keychain';
import { getCrashlytics, recordError } from '@react-native-firebase/crashlytics';
import jwt_decode from 'jwt-decode';
import { devLog } from './devUtils';
import { SSO_PROVIDER, AUTH_MODE, ANALYTICS_REASON, SSO_ERROR_CODE } from './AuthConstants';

// Tokens live in OS-backed secure storage (Keychain/Keystore), not plaintext
// AsyncStorage. Changing AUTH_KEYCHAIN_SERVICE orphans every stored credential
// with no migration path.
const AUTH_KEYCHAIN_SERVICE = 'org.sefaria.auth';
const AUTH_KEYCHAIN_USERNAME = 'sefaria_auth';
// Legacy AsyncStorage key auth tokens lived under before the move to the keychain.
const LEGACY_AUTH_ASYNC_STORAGE_KEY = 'auth';

// Maps each SSO provider to its endpoint and request body shape. Looked up
// explicitly so an unrecognized provider fails loudly instead of silently
// falling through to another provider's endpoint.
const SSO_PROVIDER_CONFIG = {
  [SSO_PROVIDER.GOOGLE]: {
    endpoint: 'api/auth/google/mobile',
    buildBody: (idToken) => ({ id_token: idToken }),
  },
  [SSO_PROVIDER.APPLE]: {
    endpoint: 'api/auth/apple/mobile',
    buildBody: (idToken, userData) => ({
      id_token: idToken,
      first_name: userData?.firstName,
      last_name: userData?.lastName,
    }),
  },
};

// In-memory short-circuit for the legacy-token migration, which otherwise runs
// an AsyncStorage read on every expired-token refresh for the life of the
// session.
//
// Semantics: true means "the legacy key is confirmed gone" -- either it was
// never there, or its contents were successfully written to the keychain and
// the legacy copy was then deleted. It is deliberately NOT set when the
// keychain write FAILS (locked device, etc.): in that case the legacy copy is
// still on disk on purpose, and the migration must stay retryable on the next
// read. Setting this flag unconditionally would strand such a user with a
// token that never makes it into the keychain.
let _legacyAuthMigrationComplete = false;

const Auth = {
  deleteUserAccount: async function() {
    await Sefaria.api.getAuthToken();
    if (!Sefaria._auth.uid) { console.log("Not signed in"); return; }
    const url = `${Sefaria.api._baseHost}api/account/delete`;
    fetch(url, {
      method: "DELETE",
      headers: {
        'Authorization': `Bearer ${Sefaria._auth.token}`,
        "Content-Type": "application/json;charset=UTF-8",
      },
    }).then(response => {
      if (response.status >= 200 && response.status < 300) {
        return response;
      } else {
        console.error('Error in response code', response.text());
        throw new Error("Bad Response Code " + response.status);
      }
    })
    .then(response => response.json())
    .then(json => {
      if ("error" in json) {
        console.error('Error in response json', json.error);
        throw new Error("Bad Response " + json.error);
      }else{
        return json;
      }
    })
    .catch(e => {
      console.error('Network Error', e);
      throw new Error("Network Error " + e);
    });
  },

  login: function(authData) {
    const url = `${Sefaria.api._baseHost}api/login/`;
    const authBody = {
      username: authData.email,
      password: authData.password,
    };
    return fetch(url, {
      method: "POST",
      body: JSON.stringify(authBody),
      headers: {
        "Content-Type": "application/json;charset=UTF-8"
      }
    });
  },
  register: function(authData) {
    const url = `${Sefaria.api._baseHost}api/register/`;
    const authBody = {
      email: authData.email,
      first_name: authData.first_name,
      last_name: authData.last_name,
      password1: authData.password,
      password2: authData.password,
      mobile_app_key: authData.mobile_app_key,
    };
    console.log(authBody, Sefaria.api.urlFormEncode(authBody));
    return fetch(url, {
      method: "POST",
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
      },
      body: Sefaria.api.urlFormEncode(authBody)
    });
  },
  socialLoginRequest: function(provider, idToken, userData) {
    const config = SSO_PROVIDER_CONFIG[provider];
    const url = `${Sefaria.api._baseHost}${config.endpoint}`;
    return fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      body: JSON.stringify(config.buildBody(idToken, userData)),
    });
  },
  // `analyticsError` is the ANALYTICS_REASON fallback AuthPage reports as the
  // analytics `error` field when `code` itself isn't a usable value (e.g. the
  // SERVER_REJECTED path below, where `code` is `data.error` and may be absent).
  _socialLoginFailure: function(code, analyticsError, error) {
    return { success: false, code, analyticsError, error };
  },
  socialLogin: async function(provider, idToken, userData) {
    const config = SSO_PROVIDER_CONFIG[provider];
    if (!config) {
      return Sefaria.api._socialLoginFailure(
        SSO_ERROR_CODE.INVALID_RESPONSE,
        ANALYTICS_REASON.INVALID_RESPONSE,
        { non_field_errors: `Unsupported SSO provider: ${provider}` },
      );
    }
    const url = `${Sefaria.api._baseHost}${config.endpoint}`;

    // Each stage is caught on its own so a client-side failure (storage,
    // parsing) isn't reported as an indistinguishable 'network_error'.
    let response;
    try {
      response = await Sefaria.api.socialLoginRequest(provider, idToken, userData);
    } catch (error) {
      recordError(getCrashlytics(), error);
      return Sefaria.api._socialLoginFailure(
        SSO_ERROR_CODE.NETWORK_ERROR,
        ANALYTICS_REASON.NETWORK_ERROR,
        { non_field_errors: `Network error during sign-in: ${error?.message}` },
      );
    }

    // A redirect silently downgrades this POST to a GET, which hits a
    // POST-only view and comes back with a non-JSON error body. Name it
    // explicitly rather than letting it surface as a mystery 405.
    //
    // Compared by URL rather than via the standard `response.redirected`
    // because React Native's fetch is the whatwg-fetch polyfill (3.6.x), whose
    // Response never assigns `redirected` -- reading it always yields
    // undefined, so that check would silently never fire on device.
    if (response.url && response.url !== url) {
      devLog(`socialLogin followed a redirect: ${url} -> ${response.url} (HTTP ${response.status})`);
      return Sefaria.api._socialLoginFailure(
        SSO_ERROR_CODE.REDIRECTED,
        ANALYTICS_REASON.INVALID_RESPONSE,
        { non_field_errors: `Request was redirected (${url} -> ${response.url}). A redirect downgrades POST to GET, so it cannot reach the sign-in endpoint.` },
      );
    }

    // Read as text first, then parse, so a non-JSON error body (HTML from a
    // proxy, say) can still be reported with its content, not just a status code.
    const rawBody = await response.text();
    let data;
    try {
      data = JSON.parse(rawBody);
    } catch (error) {
      const snippet = rawBody.replace(/\s+/g, ' ').trim().slice(0, 120);
      devLog(`socialLogin non-JSON response: ${response.status} from ${url} :: ${snippet}`);
      recordError(getCrashlytics(), error);
      return Sefaria.api._socialLoginFailure(
        SSO_ERROR_CODE.INVALID_RESPONSE,
        ANALYTICS_REASON.INVALID_RESPONSE,
        { non_field_errors: `Server returned a non-JSON response (HTTP ${response.status} from ${url}): ${snippet}` },
      );
    }

    // Valid JSON doesn't guarantee an object -- `null`, a number, or a string
    // all parse successfully, and reading data.error off those would throw.
    if (data === null || typeof data !== 'object') {
      return Sefaria.api._socialLoginFailure(
        SSO_ERROR_CODE.INVALID_RESPONSE,
        ANALYTICS_REASON.INVALID_RESPONSE,
        { non_field_errors: `Server returned an unexpected response body (HTTP ${response.status})` },
      );
    }

    if (!response.ok) {
      // data.error is server-controlled and not guaranteed to be a scalar --
      // Django form errors on a nested field (e.g. {"email": ["Already in
      // use"]}) arrive as an object. Putting that straight into `code` would
      // make truncateForAnalytics's String(value) emit the literal
      // "[object Object]" into analytics, and the same value would reach the
      // user via ssoErrorWithCode in AuthPage. Only adopt it as `code` when
      // it's actually a string or number; otherwise fall back to the same
      // INVALID_RESPONSE code used elsewhere in this function for an
      // unexpected response shape. The raw value is untouched in `data`,
      // still passed through as the third arg for __DEV__ display.
      const isScalarErrorCode = typeof data.error === 'string' || typeof data.error === 'number';
      return Sefaria.api._socialLoginFailure(
        isScalarErrorCode ? data.error : SSO_ERROR_CODE.INVALID_RESPONSE,
        ANALYTICS_REASON.SERVER_REJECTED,
        data,
      );
    }
    if (!data.access || !data.refresh) {
      // A 2xx with no tokens is not a successful sign-in.
      return Sefaria.api._socialLoginFailure(SSO_ERROR_CODE.MISSING_TOKENS, ANALYTICS_REASON.INVALID_RESPONSE, data);
    }

    try {
      await Sefaria.api.storeAuthToken(data);
    } catch (error) {
      // Sign-in succeeded but there's nowhere to keep the credentials.
      recordError(getCrashlytics(), error);
      return Sefaria.api._socialLoginFailure(
        SSO_ERROR_CODE.STORAGE_ERROR,
        ANALYTICS_REASON.STORAGE_ERROR,
        { non_field_errors: `Could not store credentials: ${error?.message}` },
      );
    }

    // Prefer the ID token's (server-verified) email over userData.email: Apple
    // only returns an email on the user's very first authorization, so later
    // sign-ins would otherwise store an undefined email.
    let tokenEmail;
    try {
      tokenEmail = jwt_decode(idToken)?.email;
    } catch (error) {
      tokenEmail = undefined;
    }
    return {
      success: true,
      email: tokenEmail || userData?.email,
      ...(data.is_new_account !== undefined ? { is_new_account: data.is_new_account } : {}),
    };
  },
  refreshToken: function(refreshToken) {
    const url = `${Sefaria.api._baseHost}api/login/refresh/`;
    const authBody = {
      refresh: refreshToken,
    };
    return fetch(url, {
      method: "POST",
      body: JSON.stringify(authBody),
      headers: {
        "Content-Type": "application/json;charset=UTF-8"
      }
    });
  },
  authenticate: async function(authData, authMode = AUTH_MODE.LOGIN) {
    try {
      const parsedRes = await (authMode === AUTH_MODE.LOGIN ? Sefaria.api.login(authData) : Sefaria.api.register(authData)).then(res => res.json());
      if (!parsedRes.access) {
        return parsedRes;  // return errors
      } else if (!parsedRes.refresh) {
        // A 2xx response with an access token but no refresh token must not be
        // treated as a successful login -- surface it as a field error instead.
        return { non_field_errors: "Missing authentication tokens" };
      } else {
        await Sefaria.api.storeAuthToken(parsedRes);
      }
    } catch (error) {
      recordError(getCrashlytics(), error);
      return {
        non_field_errors: "Unknown authentication error"
      };
    }

  },

  storeAuthToken: async function({ access, refresh }) {
    const decodedToken = jwt_decode(access);
    Sefaria._auth = {
      token: access,
      expires: decodedToken.exp,
      uid: decodedToken.user_id,
      refreshToken: refresh,
    };
    // AFTER_FIRST_UNLOCK (rather than the WHEN_UNLOCKED default) so a
    // background token refresh can still write to the keychain while the
    // device is locked -- WHEN_UNLOCKED would fail that write outright.
    await Keychain.setGenericPassword(AUTH_KEYCHAIN_USERNAME, JSON.stringify(Sefaria._auth), { service: AUTH_KEYCHAIN_SERVICE, accessible: Keychain.ACCESSIBLE.AFTER_FIRST_UNLOCK });
  },

  // One-time migration of auth tokens from legacy AsyncStorage into the
  // keychain, so already-logged-in users aren't signed out on upgrade.
  //
  // Reached from app init (hydrateAuthFromKeychain) AND from every
  // expired-token refresh (getAuthToken), which is why it short-circuits on
  // _legacyAuthMigrationComplete -- see that flag's declaration for why it is
  // only set on a definitive outcome and never after a failed keychain write.
  _migrateLegacyAuthToken: async function() {
    if (_legacyAuthMigrationComplete) { return; }
    const legacyAuth = await AsyncStorage.getItem(LEGACY_AUTH_ASYNC_STORAGE_KEY);
    // Nothing to migrate, now or ever: no legacy key exists.
    if (!legacyAuth) { _legacyAuthMigrationComplete = true; return; }
    let parsedLegacyAuth;
    try {
      parsedLegacyAuth = JSON.parse(legacyAuth);
    } catch (error) {
      // Malformed legacy value -- nothing recoverable, drop it.
      await AsyncStorage.removeItem(LEGACY_AUTH_ASYNC_STORAGE_KEY);
      _legacyAuthMigrationComplete = true;
      return;
    }
    if (!parsedLegacyAuth || !parsedLegacyAuth.token) {
      await AsyncStorage.removeItem(LEGACY_AUTH_ASYNC_STORAGE_KEY);
      _legacyAuthMigrationComplete = true;
      return;
    }
    // Only drop the legacy copy once the keychain write succeeds, so a failed
    // write (e.g. locked device) can retry on the next read.
    try {
      await Keychain.setGenericPassword(AUTH_KEYCHAIN_USERNAME, JSON.stringify(parsedLegacyAuth), { service: AUTH_KEYCHAIN_SERVICE, accessible: Keychain.ACCESSIBLE.AFTER_FIRST_UNLOCK });
    } catch (error) {
      // Deliberately leave _legacyAuthMigrationComplete false: the legacy copy
      // is still on disk and this must be retried on the next read.
      return;
    }
    await AsyncStorage.removeItem(LEGACY_AUTH_ASYNC_STORAGE_KEY);
    _legacyAuthMigrationComplete = true;
  },

  // Rehydrates Sefaria._auth from the Keychain (sole source of truth for the
  // session). Call once during app init; never throws, degrades to logged-out.
  hydrateAuthFromKeychain: async function() {
    await Sefaria.api._migrateLegacyAuthToken();
    try {
      const credentials = await Keychain.getGenericPassword({ service: AUTH_KEYCHAIN_SERVICE });
      Sefaria._auth = (credentials && JSON.parse(credentials.password)) || {};
    } catch (error) {
      recordError(getCrashlytics(), error);
      Sefaria._auth = {};
    }
    if (!Sefaria._auth.uid) { return false; /* logged out */ }
    // If the token is expired (or otherwise invalid), getAuthToken() will
    // walk the refresh-token path itself, clearing auth storage if that also
    // fails.
    await Sefaria.api.getAuthToken();
    return !!Sefaria._auth.uid;
  },

  getAuthToken: async function() {
    if (!Object.keys(Sefaria._auth).length) { return; /* logged out */ }
    const currTime = Sefaria.util.epoch_time();
    if (!Sefaria._auth.token || Sefaria._auth.expires <= currTime) {
      // Cheap no-op once the migration has a definitive outcome; still retries
      // for the one case that needs it (keychain write previously failed).
      await Sefaria.api._migrateLegacyAuthToken();
      try {
        const credentials = await Keychain.getGenericPassword({ service: AUTH_KEYCHAIN_SERVICE });
        Sefaria._auth = (credentials && JSON.parse(credentials.password)) || {};
        if (!Sefaria._auth.token) { throw new Error("no token!"); }
        if (Sefaria._auth.expires <= currTime) { throw new Error("expired token"); }
        return;  // token is valid
      } catch (error) {
        // Covers a stale/expired/missing token as well as a Keychain read
        // failure (locked device, corrupt entry) -- in every case, fall back
        // to attempting a refresh with whatever refreshToken we last had.
        const parsedRes = await Sefaria.api.refreshToken(Sefaria._auth.refreshToken).then(res => res.json());
        if (!parsedRes.access) {
          Sefaria.api.clearAuthStorage();
        } else {
          Sefaria.api.storeAuthToken(parsedRes);
        }
      }
    }
  },
  clearAuthStorage: async function() {
    await Keychain.resetGenericPassword({ service: AUTH_KEYCHAIN_SERVICE });
    await AsyncStorage.removeItem(LEGACY_AUTH_ASYNC_STORAGE_KEY);
    await AsyncStorage.removeItem('lastSyncTime');
    await AsyncStorage.removeItem('lastSettingsUpdateTime');
    await AsyncStorage.removeItem('hasDismissedSyncModal');
    await AsyncStorage.removeItem('hasSyncedOnce');
    await AsyncStorage.removeItem('hasSwipeDeleted');
    Sefaria._auth = {};
    Sefaria.history._hasSwipeDeleted = false;
    const hasSyncedOnce = Sefaria.history._hasSyncedOnce;
    Sefaria.history._hasSyncedOnce = false;
    if (!hasSyncedOnce) { return; /* dont fully delete data if not backed up */}

    Sefaria.history.deleteHistory(true);
  },
};

export {
  AUTH_KEYCHAIN_SERVICE,
  AUTH_KEYCHAIN_USERNAME,
  LEGACY_AUTH_ASYNC_STORAGE_KEY,
  SSO_PROVIDER_CONFIG,
};

export default Auth;
