// Generated by OrchestKit Claude Plugin
// Created: 2026-08-09

'use strict';

// Shared string enums for the auth flow. These values cross file boundaries
// (AuthPage <-> SSOButtons <-> api <-> analytics), so a typo in any one of them
// is a silent failure rather than a crash -- an unrecognized provider routes to
// the wrong endpoint, an unrecognized reason becomes a junk analytics value.
// Follows the existing convention in VocalizationEnum.js and errors.js.

export const SSO_PROVIDER = {
    GOOGLE: 'google',
    APPLE: 'apple',
};

export const AUTH_MODE = {
    LOGIN: 'login',
    REGISTER: 'register',
};

// Analytics event outcome. Paired with ANALYTICS_REASON on failure.
export const ANALYTICS_STATUS = {
    SUCCESS: 'success',
    FAILURE: 'failure',
};

export const ANALYTICS_REASON = {
    ABANDONED: 'abandoned',
    VALIDATION_FAILED: 'validation_failed',
    SERVER_REJECTED: 'server_rejected',
    CANCELLED: 'cancelled',
    MODULE_UNAVAILABLE: 'module_unavailable',
    PROVIDER_ERROR: 'provider_error',
    UNSUPPORTED_DEVICE: 'unsupported_device',
    NETWORK_ERROR: 'network_error',
    INVALID_RESPONSE: 'invalid_response',
    STORAGE_ERROR: 'storage_error',
};

// Client-side failure codes returned by Sefaria.api.socialLogin. Not a closed
// set at the UI: a non-ok server response forwards the backend's own `error`
// value instead, which is why AuthPage clamps the code before displaying it.
export const SSO_ERROR_CODE = {
    NETWORK_ERROR: 'network_error',
    REDIRECTED: 'redirected',
    INVALID_RESPONSE: 'invalid_response',
    MISSING_TOKENS: 'missing_tokens',
    STORAGE_ERROR: 'storage_error',
};
