// Generated by OrchestKit Claude Plugin
// Created: 2026-07-21

'use strict'

// Design tokens for SSO (Google/Apple) sign-in UI, sourced from the Figma spec
// (docs/superpowers/specs/2026-07-21-mobile-sso-design.md, section 2).
// Every SSO color, spacing, font size, and dimension should reference a named
// constant here rather than a hardcoded literal in Styles.js / SSOButtons.js.

export const SSOColors = {
  sefariaBlue: '#18345D',   // SSO button border + text (Figma --semantic/action/primary)
  white: '#FFFFFF',         // SSO button background
  dividerLine: '#CCCCCC',   // "or" divider line
  dividerText: '#999999',   // "or" text
};

export const SSOSpacing = {
  buttonGap: 16,      // vertical gap between Google and Apple buttons (Figma --global/dimension-200)
  sectionGap: 24,     // gap between SSO buttons section and the "or" divider
  buttonPaddingH: 24, // horizontal padding inside a button (--sds-size-space-600)
  iconTextGap: 8,     // gap between icon and label (--sds-size-space-200)
  dividerLabelGap: 16,// horizontal margin around the "or" label
};

export const SSODimensions = {
  buttonHeight: 51,
  buttonBorderWidth: 1.5, // --sds-size-stroke-border
  buttonRadius: 4,        // --space-1
  iconSize: 24,
  buttonContainerWidth: 337, // SSO buttons container width, Figma node 239-16934
};

export const SSOTypography = {
  buttonTextSize: 16,
  buttonFontWeight: '600',
  dividerTextSize: 14,
};
