import LocalizedStrings from 'react-native-localization';

module.exports = new LocalizedStrings({
  en: {
    recent: "RECENT",
    browse: "BROWSE",
    calendar: "CALENDAR",
    settings: "Settings",
    about: "About",
    feedback: "Feedback",
    dedicated: "Dedicated in honor of Henry Koschitzky by his children",
    cancel: "Cancel",
    open: "Open",
    tryAgain: "Try Again",
    ok: "OK",
    parashah: "Parashah",
    haftara: "Haftara",
    dafYomi: "Daf Yomi",
    tableOfContents: "TABLE OF CONTENTS",
    connections: "CONNECTIONS",
    noConnectionsMessage: "No connections available.",
    search: "Search",
    loading: "Loading...",
    results: "Results", // to be combined with a number, e.g. "32 Results"
    connectToSearchMessage: "Connect to the internet to search.",
    menuLanguage: "MENU LANGUAGE",
    defaultTextLanguage: "DEFAULT TEXT LANGUAGE",
    english: "ENGLISH",
    hebrew: "HEBREW",
    bilingual: "BILINGUAL",
    offlineAccess: "OFFLINE ACCESS",
    offlineAccessMessage: "Requires ~280MB of storage on your device.",
    downloadInProgress: "Download in progress",
    textsDownloaded: "texts downloaded", // to be combined with a number, e.g. "82 texts downloaded"
    downloadLibrary: "Download Library",
    deleteLibrary: "Delete Library",
    resumeDownload: "Resume Download",
    textUnavailable: "Text Unavailable",
    textUnavailableFromWebMessage: "The text you requested is not currently available from www.sefaria.org.",
    promptOpenOnWebMessage: "This text is not currently available in the mobile app. Would you like to open it on the Web?",
    noInternet: "Internet Connection Unavailable",
    noInternetMessage: "Please check your connection and try again.",
    libraryDownloading: "Library Downloading",
    libraryDownloadingMessage: "The library will download while you have the app open. You can check on the status of the download in the Settings screen.",
    confirmDeleteLibraryMessage: "Are you sure you want to delete the offline library? You will need an Internet connection to use the app.",
    delete: "Delete",
    usingOnlineLibrary: "Using Online Library",
    howToDownloadLibraryMessage: "You can download the library in the future from the Settings screen.",
    welcome: "Welcome",
    downloadLibraryRecommendedMessage: "We recommend downloading the offline library for a better experience. It requires about 280MB of storage. Otherwise you will need an Internet connection to use the app.",
    download: "Download",
    notNow: "Not Now",
    downloadPaused: "Download Paused",
    howToResumeDownloadMessage: "You can resume the download in the Settings screen.",
    downloadError: "Download Error",
    downloadErrorMessage: "Unfortunately we encountered an error downloading the library.",
    pause: "Pause"
  },
  he: {
    recent: "נצפו לאחרונה",
    browse: "טקסטים",
    calendar: "לוח יומי",
    settings: "הגדרות",
    about: "אודות",
    feedback: "Feedback",
    dedicated: "Dedicated in honor of Henry Koschitzky by his children",
    cancel: "בטל",
    open: "Open",
    tryAgain: "Try Again",
    ok: "קבל",
    parashah: "Parasha",
    haftara: "הפטרה",
    dafYomi: "דף יומי",
    tableOfContents: "תוכן העניינים",
    connections: "קישורים",
    noConnectionsMessage: "No connections available.",
    search: "חפש",
    loading: "טוען...",
    results: "תוצאות", // to be combined with a number, e.g. "32 Results"
    connectToSearchMessage: "Connect to the internet to search.",
    menuLanguage: "שפת תפריט",
    defaultTextLanguage: "DEFAULT TEXT LANGUAGE",
    english: "אנגלית",
    hebrew: "עברית",
    bilingual: "דו-לשוני",
    offlineAccess: "מצב בלתי מקוונת",
    offlineAccessMessage: "Requires ~280MB of storage on your device.",
    downloadInProgress: "Download in progress",
    textsDownloaded: "texts downloaded", // to be combined with a number, e.g. "82 texts downloaded"
    downloadLibrary: "הוריד את הספריה",
    deleteLibrary: "מחק את הספריה",
    resumeDownload: "Resume Download",
    textUnavailable: "Text Unavailable",
    textUnavailableFromWebMessage: "The text you requested is not currently available from www.sefaria.org.",
    promptOpenOnWebMessage: "This text is not currently available in the mobile app. Would you like to open it on the Web?",
    noInternet: "Internet Connection Unavailable",
    noInternetMessage: "Please check your connection and try again.",
    libraryDownloading: "Library Downloading",
    libraryDownloadingMessage: "The library will download while you have the app open. You can check on the status of the download in the Settings screen.",
    confirmDeleteLibraryMessage: "Are you sure you want to delete the offline library? You will need an Internet connection to use the app.",
    delete: "Delete",
    usingOnlineLibrary: "Using Online Library",
    howToDownloadLibraryMessage: "You can download the library in the future from the Settings screen.",
    welcome: "ברוכים הבאים",
    downloadLibraryRecommendedMessage: "We recommend downloading the offline library for a better experience. It requires about 280MB of storage. Otherwise you will need an Internet connection to use the app.",
    download: "Download",
    notNow: "Not Now",
    downloadPaused: "Download Paused",
    howToResumeDownloadMessage: "You can resume the download in the Settings screen.",
    downloadError: "Download Error",
    downloadErrorMessage: "Unfortunately we encountered an error downloading the library.",
    pause: "Pause"
  }
});
