import LocalizedStrings from 'react-native-localization';

module.exports = new LocalizedStrings({
  en: {
    recent: "RECENT",
    browse: "BROWSE",
    calendar: "CALENDAR",
    settings: "Settings",
    about: "About",
    feedback: "Feedback",
    dedicated: "Dedicated in honor of Henry Koschitzky by his children",
    cancel: "Cancel",
    open: "Open",
    tryAgain: "Try Again",
    ok: "OK",
    parashah: "Parashah",
    haftara: "Haftara",
    dafYomi: "Daf Yomi",
    tableOfContents: "TABLE OF CONTENTS",
    connections: "CONNECTIONS",
    noConnectionsMessage: "No connections available.",
    search: "Search",
    loading: "Loading...",
    loadingFilters: "Loading Filters...",
    results: "Results", // to be combined with a number, e.g. "32 Results"
    connectToSearchMessage: "Connect to the internet to search.",
    menuLanguage: "MENU LANGUAGE",
    defaultTextLanguage: "DEFAULT TEXT LANGUAGE",
    english: "ENGLISH",
    hebrew: "HEBREW",
    bilingual: "BILINGUAL",
    offlineAccess: "OFFLINE ACCESS",
    offlineAccessMessage: "Requires ~280MB of storage on your device.",
    downloadInProgress: "Download in progress",
    textsDownloaded: "texts downloaded", // to be combined with a number, e.g. "82 texts downloaded"
    downloadLibrary: "Download Library",
    deleteLibrary: "Delete Library",
    resumeDownload: "Resume Download",
    textUnavailable: "Text Unavailable",
    textUnavailableFromWebMessage: "The text you requested is not currently available from www.sefaria.org.",
    promptOpenOnWebMessage: "This text is not currently available in the mobile app. Would you like to open it on the Web?",
    noInternet: "Internet Connection Unavailable",
    noInternetMessage: "Please check your connection and try again.",
    libraryDownloading: "Library Downloading",
    libraryDownloadingMessage: "The library will download while you have the app open. You can check on the status of the download in the Settings screen.",
    confirmDeleteLibraryMessage: "Are you sure you want to delete the offline library? You will need an Internet connection to use the app.",
    delete: "Delete",
    usingOnlineLibrary: "Using Online Library",
    howToDownloadLibraryMessage: "You can download the library in the future from the Settings screen.",
    welcome: "Welcome",
    downloadLibraryRecommendedMessage: "We recommend downloading the offline library for a better experience. It requires about 280MB of storage. Otherwise you will need an Internet connection to use the app.",
    download: "Download",
    notNow: "Not Now",
    downloadPaused: "Download Paused",
    howToResumeDownloadMessage: "You can resume the download in the Settings screen.",
    downloadError: "Download Error",
    downloadErrorMessage: "Unfortunately we encountered an error downloading the library.",
    pause: "Pause",
    updateLater: "Update Later",
    howToUpdateLibraryMessage: "You can update your library in the future from the Settings screen.",
    updateLibrary: "Library Updates",
    updatesAvailable: "texts have updates available.", // to be combined with a number, e.g. "14 texts have..."
    updatesAvailableMessage: "texts have updates available. Would you like to download them now?", // to be combined with a number, e.g. "14 texts have..."
    libraryUpToDate: "Library Up To Date",
    libraryUpToDateMessage: "You have the most current version of the Sefaria Library for iOS.",
    checkForUpdates: "Check for Updates",
    downloadUpdates: "Download Updates",
    back: "Back",
    clearAll: "Clear All",
    filter: "FILTER",
    sortBy: "SORT BY",
    chronological: "Chronological",
    relevance: "Relevance",
    exactSearch: "EXACT SEARCH",
    on: "On",
    off: "Off",
    filterByText: "FILTER BY TEXT"
  },
  he: {
    recent: "נצפו לאחרונה",
    browse: "טקסטים",
    calendar: "לוח יומי",
    settings: "הגדרות",
    about: "אודות",
    feedback: "משוב",
    dedicated: "נתרם לכבודו של הנרי קושיצקי על ידי ילדיו",
    cancel: "בטל",
    open: "פתח",
    tryAgain: "נסה שוב",
    ok: "אישור",
    parashah: "פרשה",
    haftara: "הפטרה",
    dafYomi: "דף יומי",
    tableOfContents: "תוכן העניינים",
    connections: "קישורים",
    noConnectionsMessage: "אין קישורים",
    search: "חפש",
    loading: "טוען...",
    loadingFilters: "טוען מסננים...",
    results: "תוצאות", // to be combined with a number, e.g. "32 Results"
    connectToSearchMessage: "התחבר לאינטרנט כדי לבצע חיפוש",
    menuLanguage: "שפת תפריט",
    defaultTextLanguage: "שפת ברירת מחדל לקריאה בטקסטים",
    english: "אנגלית",
    hebrew: "עברית",
    bilingual: "דו-לשוני",
    offlineAccess: "מצב בלתי מקוון",
    offlineAccessMessage: "הורדת הספריה דורשת ~280MB משטח האחסון של הטלפון שלך",
    downloadInProgress: "הורדה מתבצעת",
    textsDownloaded: "טקסטים הורדו בהצלחה", // to be combined with a number, e.g. "82 texts downloaded"
    downloadLibrary: "הורד את הספריה",
    deleteLibrary: "מחק את הספריה",
    resumeDownload: "המשך הורדה",
    textUnavailable: "טקסט לא זמין",
    textUnavailableFromWebMessage: "הטקסט אותו ביקשת אינו זמין כרגע מwww.sefaria.org.",
    promptOpenOnWebMessage: "הטקסט הזה אינו זמין כרגע באפליקציה, האם תרצה לפתוח אותו באתר האינטרנט?",
    noInternet: "חיבור רשת אינו זמין",
    noInternetMessage: "אנא בדוק את מצב החיבור שלך ונסה שוב",
    libraryDownloading: "קבצי הספריה בהורדה",
    libraryDownloadingMessage: "קבצי הספריה יורדו מהרשת בזמן שהאפליקציה פתוחה. ניתן לבדוק את התקדמות ההורדה במסך ההגדרות.",
    confirmDeleteLibraryMessage: "האם ברצונך למחוק את הספריה מזכרון המכשיר? יידרש חיבור רשת פעיל בכדי להשתמש באפליקציה.",
    delete: "מחק",
    usingOnlineLibrary: "האפליקציה במצב מקוון בלבד",
    howToDownloadLibraryMessage: "תוכל להוריד את הספריה הבלתי מקוונת בכל עת ממסך ההגדרות.",
    welcome: "ברוכים הבאים",
    downloadLibraryRecommendedMessage: "אנו ממליצים על הורדה ושימוש בקבצי הספריה הבלתי מקוונת. שימוש בגרסה זו מצריך כ280MB של אחסון במכשיר. אחרת יידרש חיבור רשת פעיל בכדי להשתמש באפליקציה.",
    download: "הורד",
    notNow: "לא כעת",
    downloadPaused: "הורדה נעצרה",
    howToResumeDownloadMessage: "ניתן לחדש את ההורדה ממסך ההגדרות.",
    downloadError: "שגיאה בהורדה",
    downloadErrorMessage: "לצערנו ארעה תקלה בזמן ההורדה",
    pause: "עצור",
    updateLater: "עדכן אחר כך",
    howToUpdateLibraryMessage: "תוכל לעדכן את הספריה הבלתי מקוונת בעתיד ממסך ההגדרות",
    updateLibrary: "עדכונים לספריה הבלתי מקוונת",
    updatesAvailable: "עדכוני טקסט קיימים", // to be combined with a number, e.g. "14 texts have..."
    updatesAvailableMessage: "קיימים עדכונים לטקסטים. האם תרצה להוריד אותם כעת?", // to be combined with a number, e.g. "14 texts have..."
    libraryUpToDate: "הספריה מעודכנת",
    libraryUpToDateMessage: "הגרסה העדכנית ביותר של הספרייה הבלתי מקוונת ל-iOS מעודכנת במכשירך",
    checkForUpdates: "בדוק עדכונים קיימים",
    downloadUpdates: "הורד עדכונים",
    back: "חזור",
    clearAll: "נקה הכל",
    filter: "סינון",
    sortBy: "מיון לפי",
    chronological: "כרונולוגי",
    relevance: "רלוונטיות",
    exactSearch: "חיפוש מדויק",
    on: "פעיל",
    off: "כבוי",
    filterByText: "סינון לפי טקסט"
  }
});
