name: Run BrowserStack Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Clean npm cache
      working-directory: android
      run: npm cache clean --force

    - name: Clean logs-test directory
      working-directory: android
      run: |
        if [ -d logs-test ]; then rm -rf logs-test/*; else mkdir logs-test; fi

    - name: Install Dependencies
      working-directory: android
      run: npm install

    - name: Run Tests on BrowserStack
      working-directory: android
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        BROWSERSTACK_APP_ID: ${{ secrets.BROWSERSTACK_APP_ID }}
        RUN_ENV: browserstack
      run: npm test

    - name: Upload all test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-test
        path: android/logs-test/
        if-no-files-found: warn

    - name: Upload diff-images if tests fail
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: diff-images
        path: ./android/diff-images
        if-no-files-found: ignore