# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :android

platform :android do

  desc "Builds a release for internal testing deployed via the Google Play Store"
  lane :testrelease do |options|
    gradle(task: "clean")

    gradle(
      task: "assemble",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => "kstore.jks",
        "android.injected.signing.store.password" => options[:storepass],
        "android.injected.signing.key.alias" => "kstore",
        "android.injected.signing.key.password" => options[:storepass],
      }
    )

    upload_to_play_store(track: 'internal')
  end
end
