// Generated by OrchestKit Claude Plugin
// Created: 2026-08-16

import '../sefaria';
import * as Keychain from 'react-native-keychain';

// react-native-keychain has no jest mock in this repo and its native bindings
// aren't safe to load under Jest, so this stands in for the module directly.
jest.mock('react-native-keychain', () => ({
  ACCESSIBLE: { AFTER_FIRST_UNLOCK: 'AFTER_FIRST_UNLOCK' },
  getGenericPassword: jest.fn(),
  setGenericPassword: jest.fn(),
  resetGenericPassword: jest.fn(),
}));

// Regression coverage for Fix 1: a cold start with no connectivity must
// degrade to "keep the existing session", not sign the user out -- see the
// hydrateAuthFromKeychain/getAuthToken comments in auth.js.
describe('hydrateAuthFromKeychain offline degradation', () => {
  let originalFetch;
  const expiredCredentials = {
    token: 'expired-token',
    uid: 'test-uid',
    expires: 1, // epoch second 1 -- always in the past
    refreshToken: 'refresh-token',
  };

  beforeEach(() => {
    originalFetch = global.fetch;
    Keychain.getGenericPassword.mockReset();
    Keychain.setGenericPassword.mockReset().mockResolvedValue(true);
    Keychain.resetGenericPassword.mockReset().mockResolvedValue(true);
    Keychain.getGenericPassword.mockResolvedValue({ password: JSON.stringify(expiredCredentials) });
    Sefaria._auth = {};
  });

  afterEach(() => {
    global.fetch = originalFetch;
  });

  test('a network failure refreshing an expired token keeps the existing session (cold start offline)', async () => {
    global.fetch = jest.fn(() => Promise.reject(new Error('Network request failed')));

    const result = await Sefaria.api.hydrateAuthFromKeychain();

    expect(result).toBe(true);
    expect(Sefaria._auth.uid).toBe('test-uid');
    expect(Keychain.resetGenericPassword).not.toHaveBeenCalled();
  });

  test('a captive portal (non-JSON refresh response) also keeps the existing session', async () => {
    global.fetch = jest.fn(() => Promise.resolve({ json: () => Promise.reject(new Error('Unexpected token <')) }));

    const result = await Sefaria.api.hydrateAuthFromKeychain();

    expect(result).toBe(true);
    expect(Sefaria._auth.uid).toBe('test-uid');
    expect(Keychain.resetGenericPassword).not.toHaveBeenCalled();
  });

  test('a server response that genuinely rejects the refresh token still signs out', async () => {
    global.fetch = jest.fn(() => Promise.resolve({ json: () => Promise.resolve({ detail: 'Token is invalid or expired' }) }));

    const result = await Sefaria.api.hydrateAuthFromKeychain();

    expect(result).toBe(false);
    expect(Sefaria._auth.uid).toBeUndefined();
    expect(Keychain.resetGenericPassword).toHaveBeenCalled();
  });

  test('hydrateAuthFromKeychain never rejects even on an offline cold start', async () => {
    global.fetch = jest.fn(() => Promise.reject(new Error('Network request failed')));
    await expect(Sefaria.api.hydrateAuthFromKeychain()).resolves.toBe(true);
  });
});
