// Generated by OrchestKit Claude Plugin
// Created: 2026-08-06

import { ssoErrorWithCode } from '../AuthPage';
import strings from '../LocalizedStrings';

// Release builds show only strings.ssoErrorGeneric, which made every SSO
// failure look the same from a screenshot. These pin the code being appended,
// and pin the clamping -- api.js falls back to the backend's `data.error` on a
// non-ok response, so the value is server-controlled and must not reach the UI
// verbatim.
describe('ssoErrorWithCode', () => {
  test.each([
    'network_error',
    'redirected',
    'invalid_response',
    'missing_tokens',
    'storage_error',
    'auth.social_signin_failed',
  ])('appends the %s code to the generic message', (code) => {
    expect(ssoErrorWithCode(code)).toBe(`${strings.ssoErrorGeneric} (${code})`);
  });

  test.each([undefined, null, ''])('falls back to the bare message for %p', (code) => {
    expect(ssoErrorWithCode(code)).toBe(strings.ssoErrorGeneric);
  });

  test('strips characters outside an identifier shape', () => {
    // Only [a-zA-Z0-9._-] survives, so angle brackets, spaces, parens and `=`
    // are all removed -- nothing server-supplied can render as markup.
    expect(ssoErrorWithCode('<img src=x onerror=alert(1)>')).toBe(
      `${strings.ssoErrorGeneric} (imgsrcxonerroralert1)`
    );
  });

  test('clamps a long server-controlled code to 40 characters', () => {
    const long = 'a'.repeat(200);
    const rendered = ssoErrorWithCode(long);
    expect(rendered).toBe(`${strings.ssoErrorGeneric} (${'a'.repeat(40)})`);
  });

  test('never renders whitespace-only codes', () => {
    expect(ssoErrorWithCode('   ')).toBe(strings.ssoErrorGeneric);
  });
});
