name: 🚀 Deploy Android
on:
  workflow_dispatch:

jobs:
  android-deploy:
    name: Android → Internal Testing
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK tools
        run: |
          # install the two new casks in lieu of the old android-sdk
          brew install --cask android-commandlinetools android-platform-tools

          # point ANDROID_SDK_ROOT at "latest" cmdline-tools
          ANDROID_SDK_ROOT="$(brew --prefix)/share/android-commandlinetools/cmdline-tools/latest"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

          # add sdkmanager + adb to PATH
          echo "$ANDROID_SDK_ROOT/bin" >> $GITHUB_PATH
          echo "$(brew --prefix)/share/android-platform-tools" >> $GITHUB_PATH

          # accept licenses & install the bits you need
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"

      - name: Install Bundler & Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Decode Play Store JSON
        run: |
          echo "${{ secrets.PLAY_JSON_BASE64 }}" \
            | base64 --decode \
            > android/fastlane/production-deployment-a34193910650.json

      - name: Decode Android Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" \
            | base64 --decode \
            > android/app/upload-kstore.keystore

      - name: Run Fastlane Android testrelease
        working-directory: android
        run: |
          bundle exec fastlane android testrelease storepass:${{ secrets.STOREPASS }}
