name: 🚀 Deploy Android
on:
  workflow_dispatch:

jobs:
  android-deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Android SDK
        run: |
          echo "ANDROID_HOME=/Users/runner/Library/Android/sdk" >> $GITHUB_ENV

          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -fsSL https://dl.google.com/android/repository/commandlinetools-mac-9477386_latest.zip \
            -o cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          rm cmdline-tools.zip
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools"  >> $GITHUB_PATH
          echo "$ANDROID_HOME/emulator"       >> $GITHUB_PATH

          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"

      - name: Install Bundler & Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Decode Play Store JSON
        run: |
          echo "${{ secrets.PLAY_JSON_BASE64 }}" \
            | base64 --decode \
            > android/fastlane/production-deployment-a34193910650.json

      - name: Decode Android Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" \
            | base64 --decode \
            > android/app/upload-kstore.keystore

      - name: Create envvars.sh file
        run: |
          echo "export SOURCE_SERVER=\"https://readonly.sefaria.org/\"" >> scripts/envvars.sh
          echo "export SOURCE_UNIX_PATH=\"static/ios-export/\"" >> scripts/envvars.sh

      - name: Run Fastlane Android testrelease
        working-directory: android
        run: |
          bundle exec fastlane android testrelease storepass:${{ secrets.STOREPASS }}
